### ISSUE TITLE
Persistent ServiceClient Connections

### ISSUE THREAD

**Issue by robotsorcerer** [Xamla/torch-ros#11]
I'm here again :laughing: 

Does the ServiceClient API support roscpp [persistent calls](http://wiki.ros.org/roscpp/Overview/Services#Persistent_Connections) as described in the link?

If so, what's the API for setting it to true?

**Comment by andreaskoepf** [comment]
I have not explicitely tested them but the methods support the `persistent` argument. e.g. see [NodeHandle:serviceClient(service_name, service_spec, persistent, header_values)](https://github.com/Xamla/torch-ros/blob/master/lua/NodeHandle.lua#L208). You can also ask if a service client is persistent with [ServiceClient:isPersistent()](https://github.com/Xamla/torch-ros/blob/master/lua/ServiceClient.lua#L90).

**Comment by robotsorcerer** [comment]
I did test them and they work. Just so you know.
