### ISSUE TITLE
get depth from sensor topic

### ISSUE THREAD

**Issue by zlt1991** [Xamla/torch-ros#13]
I have encountered a problem with getting depth data from sensor(like kinect). I simulated environment in gazebo and subscribed sensor topic in torch. I can get correct rgb picture, but noise data from depth. In addition, size of depth data is expected 480×640, however, I got size of 1228800 (may mean 960×1280). here is my code:

require 'mobdebug'.start()
require 'image'
ros = require 'ros'
local depth
local rgb
ros.init('subscribe_demo')
spinner = ros.AsyncSpinner()
spinner:start()
nodehandle = ros.NodeHandle()
subscriber_depth = nodehandle:subscribe("/head_camera/depth_registered/image_raw",'sensor_msgs/Image', 1)
subscriber_rgb = nodehandle:subscribe("/head_camera/rgb/image_raw", 'sensor_msgs/Image', 1)
-- register a callback function that will be triggered from ros.spinOnce() when a message is available.
subscriber_depth:registerCallback(function(msg, header)
  depth=msg.data
  print(header)
  print(depth:size())
end)
subscriber_rgb:registerCallback(function(msg, header)
  rgb=msg.data
  print(rgb:size())
end)

while ros.ok() do
  ros.spinOnce()
  sys.sleep(0.5)
  
  rgb=rgb:resize(480,640,3):permute(3,1,2)--:div(256)--:
  rgb=rgb:index(1,torch.LongTensor{3,2,1})
  depth=depth:resize(960,1280)
  image.save('rgb.jpg',rgb)
  image.save('depth.jpg',depth)
end

subscriber:shutdown()
ros.shutdown()

Do you have any suggestion ?

**Comment by andreaskoepf** [comment]
The depth data normally should be 16bit per pixel (uint16 depths in mm) . I would expect a buffer size of 640x480x2 = 614400 bytes. The size of 1228800 bytes you report could mean 32 bit per pixel. Could you please check the whole header of the [sensor_msgs/Image](http://docs.ros.org/api/sensor_msgs/html/msg/Image.html) and post the values for `encoding`, `width`, `height` and `step`?

**Comment by zlt1991** [comment]
Thanks for your reply !
Yes, I think you are right. I checked the header of the sensor_msgs/image and found the encoding: 32FC1, height:480, width:640, step: 2560 (640×4).  But is there any portable way to convert the bytes to float in torch ?

**Comment by andreaskoepf** [comment]
With luajit ffi you can use `ffi.copy()` (see [ffi API](http://luajit.org/ext_ffi_api.html)) to do a memcpy between tensors, e.g. something like the following should work:

```
ffi = require 'ffi'
a = torch.ByteTensor(640*480*4)
b = torch.FloatTensor(480,640,1)
ffi.copy(b:storage():data(), a:storage():data(), a:storage():size())
```

**Comment by zlt1991** [comment]
Thanks！
