### ISSUE TITLE
Cannot run the demo

### ISSUE THREAD

**Issue by ghost** [Xamla/torch-ros#16]
I compiled torch ros by luarocks make within the torch-ros folder. (I also tried catkin_make in the ROS workspace with torch-ros in it). I had roscore running. But when I tried some demos, it kept returning errors
![screen](https://user-images.githubusercontent.com/24283641/27366670-f850d30a-568a-11e7-9776-1575e703e4e2.png)

I'm not sure what's going wrong or how should run those demos correctly? Can someone please help?

**Comment by andreaskoepf** [comment]
Are you using torch with luajit or lua 5.2? torch-ros only supports luajit. Does it compile without errors (using `luarocks make`)? what is the output if you evaluate the global `ros` variable in th? It should normally contain the NodeHandle() ctor.

**Comment by ghost** [comment]
I have luajit and lua5.1.5 installed,  but luajit returned same error as th. There is no error coming out during make & make install or just luarocks make (I tried both). 
![3](https://user-images.githubusercontent.com/24283641/27410843-6fcd21ca-572d-11e7-86e0-acbc207464ff.png)

When require 'ros' in th, it shows me:
![2](https://user-images.githubusercontent.com/24283641/27410688-7385ac98-572c-11e7-9a09-ab28493f3742.png)

It doesn't look like correct (red colour looks like error, or probably not). I'm not sure what goes wrong.

**Comment by ghost** [comment]
I removed all the stuff related to torch and lua. Re install them, luarocks make the torch-ros. Now it's working. Close issue. Thanks!
