### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jingweiz** [Xamla/torch-ros#2]
Hi there,
I try to build torch-ros but get the following error:
[  4%] Building CXX object CMakeFiles/torch-ros.dir/src/std/string.cpp.o
[  8%] Building CXX object CMakeFiles/torch-ros.dir/src/std/string_vector.cpp.o
[ 12%] Building CXX object CMakeFiles/torch-ros.dir/src/std/string_map.cpp.o
[ 16%] Building CXX object CMakeFiles/torch-ros.dir/src/std/variable.cpp.o
[ 20%] Building CXX object CMakeFiles/torch-ros.dir/src/std/variable_vector.cpp.o
[ 24%] Building CXX object CMakeFiles/torch-ros.dir/src/std/variable_table.cpp.o
[ 28%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/init.cpp.o
[ 32%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/callback_queue.cpp.o
[ 36%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/node_handle.cpp.o
[ 40%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/master.cpp.o
[ 44%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/this_node.cpp.o
[ 48%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/message_buffer.cpp.o
[ 52%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/subscriber.cpp.o
[ 56%] Building CXX object CMakeFiles/torch-ros.dir/src/ros/publisher.cpp.o
In file included from /opt/ros/indigo/include/ros/serialization.h:37:0,
                 from /opt/ros/indigo/include/ros/publisher.h:34,
                 from /opt/ros/indigo/include/ros/node_handle.h:32,
                 from /opt/ros/indigo/include/ros/ros.h:45,
                 from ~/deepnet/torch-ros/src/ros/torch-ros.h:9,
                 from ~/deepnet/torch-ros/src/ros/publisher.cpp:1:
/opt/ros/indigo/include/ros/message_traits.h: In instantiation of ‘static const char\* ros::message_traits::MD5Sum<M>::value(const M&) [with M = RawMessage]’:
/opt/ros/indigo/include/ros/message_traits.h:255:104:   required from ‘const char\* ros::message_traits::md5sum(const M&) [with M = RawMessage]’
/opt/ros/indigo/include/ros/publisher.h:112:7:   required from ‘void ros::Publisher::publish(const M&) const [with M = RawMessage]’
/home/zhang/deepnet/torch-ros/src/ros/publisher.cpp:34:20:   required from here
/opt/ros/indigo/include/ros/message_traits.h:126:34: error: ‘const class RawMessage’ has no member named ‘__getMD5Sum’
     return m.__getMD5Sum().c_str();
                                  ^
/opt/ros/indigo/include/ros/message_traits.h: In instantiation of ‘static const char\* ros::message_traits::DataType<M>::value(const M&) [with M = RawMessage]’:
/opt/ros/indigo/include/ros/message_traits.h:264:106:   required from ‘const char\* ros::message_traits::datatype(const M&) [with M = RawMessage]’
/opt/ros/indigo/include/ros/publisher.h:112:7:   required from ‘void ros::Publisher::publish(const M&) const [with M = RawMessage]’
~/deepnet/torch-ros/src/ros/publisher.cpp:34:20:   required from here
/opt/ros/indigo/include/ros/message_traits.h:143:36: error: ‘const class RawMessage’ has no member named ‘__getDataType’
     return m.__getDataType().c_str();
                                    ^
/opt/ros/indigo/include/ros/message_traits.h: In static member function ‘static const char\* ros::message_traits::MD5Sum<M>::value(const M&) [with M = RawMessage]’:
/opt/ros/indigo/include/ros/message_traits.h:127:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
/opt/ros/indigo/include/ros/message_traits.h: In static member function ‘static const char\* ros::message_traits::DataType<M>::value(const M&) [with M = RawMessage]’:
/opt/ros/indigo/include/ros/message_traits.h:144:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make[2]: **\* [CMakeFiles/torch-ros.dir/src/ros/publisher.cpp.o] Error 1
make[1]: **\* [CMakeFiles/torch-ros.dir/all] Error 2
make: **\* [all] Error 2

I'm using ros indigo so I wonder if this is a version issue.
Which version of ros is this package supported? Thanks in advance!

**Comment by jingweiz** [comment]
Ah so everything fixed after I instal md5 :)

**Comment by LiliMeng** [comment]
I have the same problem, but even install md5 by $luarocks install md5, the problem still exists.

Any suggestions?

Thanks a lot!
