### ISSUE TITLE
custom service specs

### ISSUE THREAD

**Issue by jingweiz** [Xamla/torch-ros#9]
Hi,
Is it possible to define a custom service type in torch-ros, or write a client for a custom service type?
Thanks!

**Comment by andreaskoepf** [comment]
@jingweiz Yes, it is absolutely possible to create both service client and service server with a custom service type. Any standard ROS .srv file can be used. See [this tutorial](http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv) on how to generate wrappers for other languages... We at xamla usually create a sub-package that contains only the msg and srv definitions for a project.

**Comment by jingweiz** [comment]
Great! Thanks a lot! I'll check it out!
